name: Build ğŸ ğŸ“¦ wheels

on:
  push:
    branches:
      - asahi
#  workflow_dispatch:
#  workflow_call:
#    inputs:
#      ref:
#        default: ${{ github.ref }}
#        required: false
#        type: string

jobs:
  build-py-version-specific:
    name: Build version-specific wheels ğŸ“¦
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-tags: true
        fetch-depth: 0
    - name: Install build tools
      run: |
        python -m pip install --user --upgrade pip setuptools wheel build
    - name: Build wheel
      run: |
        python -m build --wheel
    - name: Store the wheel
      uses: actions/upload-artifact@v4
      with:
        name: python-package-py${{ matrix.python-version }}
        path: dist

